"""add SavedSearch, UsageLog models and ImportSession.saved_search_id FK

Revision ID: bb9fc1dd0499
Revises: d5d7cfd238a0
Create Date: 2026-06-18 15:54:42.509387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9fc1dd0499'
down_revision: Union[str, Sequence[str], None] = 'd5d7cfd238a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_searches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('is_monitoring_enabled', sa.Boolean(), nullable=True),
    sa.Column('monitoring_interval_hours', sa.Integer(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=50), nullable=True),
    sa.Column('last_run_error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_searches_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_saved_searches_next_run', ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_searches_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_searches_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_saved_searches_user_monitoring', ['user_id', 'is_monitoring_enabled'], unique=False)

    op.create_table('usage_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fallback_provider', sa.String(length=50), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_usage_logs_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('import_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved_search_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_import_sessions_saved_search_id', 'saved_searches', ['saved_search_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_import_sessions_saved_search_id', type_='foreignkey')
        batch_op.drop_column('saved_search_id')

    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_logs_user_id'))
        batch_op.drop_index('ix_usage_logs_user_created')
        batch_op.drop_index(batch_op.f('ix_usage_logs_created_at'))

    op.drop_table('usage_logs')
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.drop_index('ix_saved_searches_user_monitoring')
        batch_op.drop_index(batch_op.f('ix_saved_searches_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_searches_next_run_at'))
        batch_op.drop_index('ix_saved_searches_next_run')
        batch_op.drop_index(batch_op.f('ix_saved_searches_created_at'))

    op.drop_table('saved_searches')
    # ### end Alembic commands ###
