"""add import sessions and related models

Revision ID: d5d7cfd238a0
Revises: 05cc16633e16
Create Date: 2026-06-18 09:11:40.354931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d7cfd238a0'
down_revision: Union[str, Sequence[str], None] = '05cc16633e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('import_type', sa.String(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=True),
    sa.Column('matched_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_session_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price_jpy', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('seller_name', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_session_id'], ['import_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ebay_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_item_id', sa.Uuid(), nullable=False),
    sa.Column('ebay_item_id', sa.String(), nullable=True),
    sa.Column('ebay_title', sa.String(), nullable=True),
    sa.Column('ebay_price_usd', sa.Float(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_status', sa.String(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profit_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ebay_match_id', sa.Uuid(), nullable=False),
    sa.Column('source_price_jpy', sa.Integer(), nullable=False),
    sa.Column('ebay_price_jpy', sa.Integer(), nullable=False),
    sa.Column('profit_jpy', sa.Integer(), nullable=False),
    sa.Column('profit_margin_pct', sa.Float(), nullable=False),
    sa.Column('exchange_rate_usd_jpy', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ebay_match_id'], ['ebay_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profit_snapshots')
    op.drop_table('ebay_matches')
    op.drop_table('source_items')
    op.drop_table('import_sessions')
    # ### end Alembic commands ###
